default: &default
  adapter: postgresql
  encoding: unicode

  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tolsky_chat_development
  password: <%= ENV["TOLSKY_CHAT_DATABASE_PASSWORD"] %>
  user: karina

test:
  <<: *default
  database: tolsky_chat_test

production:
  primary: &primary_production
    <<: *default
    database: tolsky_chat_production
    username: tolsky_chat
    password: <%= ENV["TOLSKY_CHAT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tolsky_chat_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tolsky_chat_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tolsky_chat_production_cable
    migrations_paths: db/cable_migrate
